// FrontEnd/chatbot-f1/src/app/contact/page.tsx
// src/app/contact/page.tsx
import Image from 'next/image';

export default function Contact() {
  return (
    <div className="container mx-auto px-4 py-8 flex flex-col items-center min-h-screen-minus-navbar-footer">
      <h1 className="text-4xl font-bold text-center mb-8">
        Entre em Contato!
      </h1>
      <div className="bg-gray-100 p-8 rounded-lg shadow-md w-full max-w-lg mb-8">
        <p className="text-lg mb-4">
          Nome: Vladimir Carlos Alves
        </p>
        <p className="text-lg mb-4">
          WhatsApp: <a href="https://wa.me/+5535920014611"  rel="noopener noreferrer" className="text-blue-600 hover:underline">{`+55 (35) 92001-4611`}</a>
        </p>
        <p className="text-lg mb-4">
          E-mail: <a href="mailto:vladimirca2000@gmail.com"  rel="noopener noreferrer" className="text-blue-600 hover:underline">vladimirca2000@gmail.com</a>
        </p>
        <p className="text-lg mb-4">
          LinkedIn: <a href="https://www.linkedin.com/in/vladimirca2000/"  rel="noopener noreferrer" className="text-blue-600 hover:underline">linkedin.com/in/vladimirca2000</a>
        </p>
        <p className="text-lg mb-4">
          GitHub: <a href="https://github.com/vladimirca2000"  rel="noopener noreferrer" className="text-blue-600 hover:underline">github.com/vladimirca2000</a>
        </p>
      </div>

      <h2 className="text-3xl font-bold text-center mb-4">Nossa Localização</h2>
      <div className="w-full max-w-lg h-80 bg-gray-200 rounded-lg overflow-hidden shadow-md">
        {/* Exemplo de mapa estático - substitua pela URL do seu mapa */}
        <img
          src="https://via.placeholder.com/600x400?text=Mapa+da+Localizacao"
          alt="Mapa da localização"
          className="w-full h-full object-cover"
        />
        {/* Para um mapa mais real, você pode usar um iframe do Google Maps, por exemplo: */}
        {/*
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3...YOUR_EMBED_CODE...!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x...YOUR_LOCATION_COORDS...!2z...YOUR_LOCATION_NAME...!5e0!3m2!1spt-BR!2sbr!4v..."
          width="100%"
          height="100%"
          style={{ border: 0 }}
          allowFullScreen
          loading="lazy"
          referrerPolicy="no-referrer-when-downgrade"
        ></iframe>
        */}
      </div>
    </div>
  );
}

// FrontEnd/frontend-chatbot/pages/contact.vue
<!-- pages/contact.vue -->
<template>
  <div class="min-h-screen bg-white py-8">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Page Header -->
      <div class="text-center mb-12">
        <h1 class="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">
          Contato
        </h1>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <!-- Contact Information -->
        <div class="space-y-6">
          <div class="bg-gray-50 rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-900 mb-6">Informações de Contato</h2>
            
            <div class="space-y-4">
              <div class="flex items-center space-x-3">
                <span class="font-semibold text-gray-700 w-20">Nome:</span>
                <span class="text-gray-900">Vladimir Carlos Alves</span>
              </div>

              <div class="flex items-center space-x-3">
                <span class="font-semibold text-gray-700 w-20">WhatsApp:</span>
                <a 
                  href="tel:+5511999999999"
                  class="text-blue-600 hover:text-blue-800 transition-colors duration-200"
                >
                  (11) 99999-9999
                </a>
              </div>

              <div class="flex items-center space-x-3">
                <span class="font-semibold text-gray-700 w-20">E-mail:</span>
                <a 
                  href="mailto:vladimir@exemplo.com"
                  class="text-blue-600 hover:text-blue-800 transition-colors duration-200"
                >
                  vladimir@exemplo.com
                </a>
              </div>

              <div class="flex items-center space-x-3">
                <span class="font-semibold text-gray-700 w-20">LinkedIn:</span>
                <a 
                  href="https://linkedin.com/in/vladimir-carlos-alves"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-blue-600 hover:text-blue-800 transition-colors duration-200"
                >
                  linkedin.com/in/vladimir-carlos-alves
                </a>
              </div>

              <div class="flex items-center space-x-3">
                <span class="font-semibold text-gray-700 w-20">GitHub:</span>
                <a 
                  href="https://github.com/vladimir-carlos-alves"
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-blue-600 hover:text-blue-800 transition-colors duration-200"
                >
                  github.com/vladimir-carlos-alves
                </a>
              </div>
            </div>
          </div>
        </div>

        <!-- Map Section -->
        <div class="space-y-6">
          <div class="bg-gray-50 rounded-lg p-6">
            <h2 class="text-2xl font-bold text-gray-900 mb-6">Localização</h2>
            
            <div class="h-80 bg-gray-200 rounded-lg flex items-center justify-center">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.1975605576845!2d-46.6634!3d-23.5615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce59c8da0aa315%3A0xd59f9431f2c9776a!2sSao%20Paulo%2C%20SP%2C%20Brazil!5e0!3m2!1sen!2s!4v1644123456789!5m2!1sen!2s"
                width="100%"
                height="100%"
                style="border:0"
                loading="lazy"
                allowfullscreen
                referrerpolicy="no-referrer-when-downgrade"
                class="w-full h-full rounded-lg"
                title="Mapa da localização de Vladimir Carlos Alves"
              ></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// Página de contato simples conforme especificação
useHead({
  title: 'Contato - Vladimir Carlos Alves',
  meta: [
    {
      name: 'description',
      content: 'Entre em contato com Vladimir Carlos Alves'
    }
  ]
})
</script>
